---
# tasks file for gocd

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: gocd

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: gocd

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: gocd

- name: Create Go CD server defaults file
  template: >
    src=gocd_server_default.j2
    dest=/etc/default/go-server
    owner=go
    group=go
    mode=0644
  when: gocd_server
  notify: restart gocd server
  tags:
    - gocd
    - gocd_server

- name: Create Go CD agent defaults file
  template: >
    src=gocd_agent_default.j2
    dest=/etc/default/go-agent
    owner=go
    group=go
    mode=0644
  when: gocd_agent
  notify: restart gocd agent
  tags:
    - gocd
    - gocd_agent

- name: Ensure Go CD server is started and enabled on boot
  service: name={{ gocd_server_service_name }} state=started enabled=yes
  when: gocd_server
  tags:
    - gocd
    - gocd_server

- name: Ensure Go CD agent is started and enabled on boot
  service: name={{ gocd_agent_service_name }} state=started enabled=yes
  when: gocd_agent
  tags:
    - gocd
    - gocd_agent
