---
# tasks file for gocd (Ubuntu specific)

- name: Add Go CD APT key
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=8816C449
    state=present
  tags: gocd

- name: Add Go CD APT repository
  apt_repository: >
    repo='deb https://download.go.cd /'
    state=present
  tags: gocd

- name: Install Go CD server packages
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    force=yes
  with_items: gocd_server_packages
  when: gocd_server
  tags:
    - gocd
    - gocd_server

- name: Install Go CD agent packages
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    force=yes
  with_items: gocd_agent_packages
  when: gocd_agent
  tags:
    - gocd
    - gocd_agent
